language: R
sudo: false
cache: packages
dist: trusty

r:
  - release
  - devel

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      r: devel

env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --run-donttest"

notifications:
  email: false

#before_install:
#    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

r_packages:
  - ggplot2
  - covr

#r_github_packages: modelOriented/DALEX

after_success:
  - Rscript -e 'library(covr); codecov()'

